### ISSUE TITLE
No support for emojis or emoticons

### ISSUE THREAD

**Issue by jmfulgham** [bobby-brennan/rss-parser#104]
Any data that I'm pulling that includes emojis gives me weird characters:
What I'm getting:
Howdy ðWeâre the folks

How it should look:
Howdy 👋We’re the folks at

Is there any fix for this? Thank you :)

**Comment by bobby-brennan** [comment]
Can you share the URL of the feed, or a minimal example?

**Comment by jmfulgham** [comment]
https://remoteok.io/remote-jobs.rss is the feed I'm using.

**Comment by bobby-brennan** [comment]
This appears to be a problem with the feed itself, rather than `rss-parser`. The characters appear broken in Chrome browser as well.

You should contact the host about the broken encodings. They may need to specify `encoding="UTF-8"` in their xml or HTTP response. I suspect there's a deeper bug though.
