### ISSUE TITLE
Does not fetch description for Youtube Rss

### ISSUE THREAD

**Issue by adityathebe** [bobby-brennan/rss-parser#106]

**Comment by bobby-brennan** [comment]
Can you add some more details here? Maybe a link to the feed you're using?

**Comment by adityathebe** [comment]
# [Feed Url](https://www.youtube.com/feeds/videos.xml?channel_id=UC587BAG9cLTYtJ7Q4CqcOnw)

```js
let Parser = require('rss-parser');
let parser = new Parser();

(async () => {

  let feed = await parser.parseURL('https://www.youtube.com/feeds/videos.xml?channel_id=UC587BAG9cLTYtJ7Q4CqcOnw');

  console.log(feed.items[0]);
})();

// { title: 'Market Update: BTFD Mode',
//  link: 'https://www.youtube.com/watch?v=iYFhzX8QF9U',
//   pubDate: '2019-04-09T03:08:01.000Z',
//   author: 'Josh Olszewicz',
//   id: 'yt:video:iYFhzX8QF9U',
//   isoDate: '2019-04-09T03:08:01.000Z' }
```

![](http://i.imgur.com/KHGqnAE.png)

**Comment by bobby-brennan** [comment]
`media:description` isn't a standard field. You can get it using [the custom fields option](https://github.com/bobby-brennan/rss-parser#custom-fields)

```js
let parser = new Parser({
  customFields: {
    item: ['media:description','description'],
  }
});
```

**Comment by adityathebe** [comment]
Is it possible to access nested custom fields ? **media:description** is nested inside **media:group**

**Comment by bobby-brennan** [comment]
Unfortunately no. But if you grab `media:group`, it will have the `media:description` info inside it.

**Comment by adityathebe** [comment]
Okay thanks !

**Comment by waptik** [comment]
Sorry to ask my question in here as it's related to this one. After adding media:group, i get some objects in the output. My question is how to display contents from items with methods?
the ouput:
`{ channelId: 'UCvPVim-7fTuPxGyPjMnZhPg',
  videoId: 'GEiTvO288NE',
  publishedAt: '2019-03-19T20:18:35+00:00',
  updatedAt: '2019-03-19T21:17:12+00:00',
  videoUrl:
   { '$':
      { rel: 'alternate',
        href: 'https://www.youtube.com/watch?v=GEiTvO288NE' } },
  mediaDetails:
   { 'media:title': [ 'Opening song Tensei shitara Slime Datta Ken v2' ],
     'media:content': [ [Object] ],
     'media:thumbnail': [ [Object] ],
     'media:description':
      [ 'The second opening theme song of Tensei shitara Slime Datta Ken (That time I got reincarnated as a slime)\n\nAnime: Tensei shitara Slime Datta
Ken\n\n----------------------- Disclaimer --------------------------------------\nWe do not own any of the original video contents. All original video contents belong to their respective owners.\n\n✔ Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for "fair use" for purposes such as criticism, comment, news reporting, teaching, scholarship, and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Non-profit, educational or personal use tips the balance in favor of fair use' ],
     'media:community': [ [Object] ] },
  title: 'Opening song Tensei shitara Slime Datta Ken v2',
  link: 'https://www.youtube.com/watch?v=GEiTvO288NE',
  pubDate: '2019-03-19T20:18:35.000Z',
  author: 'AnimeSpot',
  id: 'yt:video:GEiTvO288NE',
  isoDate: '2019-03-19T20:18:35.000Z' }`

input:
`customFields: {
            feed: [
                    //['media:group'],//[fields.feed],
                ],
            item: [
                    ['yt:channelId', 'channelId'],
                    ['yt:videoId', 'videoId'],
                    ['published', 'publishedAt'],
                    ['updated', 'updatedAt'],
                    ['link', 'videoUrl'],
                    ['name', 'authorName'],
                    ['url', 'authorProfile'],
                    ['media:group', 'mediaDetails'],
                    ['media:description', 'description'],
                    ['media:title', 'title'],
                    ['media:content', 'videoFile'],
                    ['media:thumbnail', 'thumbnail']//[fields.item]
                ]
        }`
rss feed url:
`https://www.youtube.com/feeds/videos.xml?channel_id=UCvPVim-7fTuPxGyPjMnZhPg`

**Comment by bobby-brennan** [comment]
You should be able to get at it with e.g. `console.log(channel.mediaDetails['media:title'][0]`

**Comment by waptik** [comment]
> You should be able to get at it with e.g. `console.log(channel.mediaDetails['media:title'][0]`

Oh thanks. I was expecting it to show the normal way. When passing it to JSON.stringify(), everything shows up! e.g. `(async () => {
	const feed = await parser.parseURL(link);
	console.log(JSON.stringify(feed));
})();
Thanks though.`
