### ISSUE TITLE
cors and importing library ES2015 way

### ISSUE THREAD

**Issue by agrigory1982** [bobby-brennan/rss-parser#52]
Hello, I want to parse rss-feeds client side.

I'm getting error:
Failed to load https://www.reddit.com/.rss: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://test.com:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

How to deal with this?
I understand this is because I'm parsing feeds client side.

My code is:
    import * as Parser from 'rss-parser';
    let parser = new Parser();
    parser.parseURL('https://www.reddit.com/.rss', function(err, feed) {
      console.log(feed.title);
      feed.items.forEach(entry => console.log(entry.title + ':' + entry.link));
    });

Am I importing the library correctly?

Thank you!

**Comment by bobby-brennan** [comment]
Unfortunately there are some URLs that simply can't be loaded in the
browser due to CORS security issues. The only way to get around it is by
using a proxy (unless you have access to the server hosting the RSS feed).
There are some free CORS proxies out there:

https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347

On Jan 18, 2018 7:20 PM, "agrigory1982" <notifications@github.com> wrote:

Hello, I want to parse rss-feeds client side.

I'm getting error:
Failed to load https://www.reddit.com/.rss: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://test.com:8080' is therefore not allowed access. If an opaque
response serves your needs, set the request's mode to 'no-cors' to fetch
the resource with CORS disabled.

How to deal with this?
I understand this is because I'm parsing feeds client side.

My code is:
import * as Parser from 'rss-parser';
let parser = new Parser();
parser.parseURL('https://www.reddit.com/.rss', function(err, feed) {
console.log(feed.title);
feed.items.forEach(entry => console.log(entry.title + ':' + entry.link));
});

Am I importing the library correctly?

Thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bobby-brennan/rss-parser/issues/52>, or mute the thread

**Comment by bobby-brennan** [comment]
I'll change the example in the readme since Reddit has this CORS problem

**Comment by agrigory1982** [comment]
Thank you! this is something I suspected. Probably, we will have to write and deploy our own cors proxy just for rss. Thank you for listing options!
