### ISSUE TITLE
over ride parseURL proxy settings?

### ISSUE THREAD

**Issue by scottie** [bobby-brennan/rss-parser#88]
can we override the parseURL function with custom proxies? or something to get the required effect?

maybe??
```
let parser = new Parser({
  proxy: "133.21.34.1:8080",
});
```

**Comment by bobby-brennan** [comment]
Sorry, don't understand what you're looking for here. Couldn't you just replace the host in the URL with `133.21.34.1:8080`?

**Comment by scottie** [comment]
how would replacing the host with a random ip achieve anything ?

**Comment by bobby-brennan** [comment]
Wouldn't the HTTP request you issue just be something like `http://133.21.34.1:8080/SOMEURL.com/RSS/FEED.ATOM`? Why not just pass that URL to rss-parser? If you need to pass the target host as a header, [you can do that too](https://github.com/bobby-brennan/rss-parser#headers)

Making the HTTP request yourself is probably the best way to go if the above isn't feasible.

**Comment by bobby-brennan** [comment]
To answer my own question: I think the request here is to support proxies that use HTTP Tunneling. The `request` library [supports this](https://github.com/request/request#proxies), but we don't use `request` in order to keep the browser distro size down. 

I think adding HTTP tunneling is out-of-scope for this project, so I'm going to close this issue.

Anyone who wants to use a proxy, I would suggest using the `request` library to download the RSS XML yourself, then passing the result to `parser.parseString()`.
